databases:
  - name: flex-pay-database
    databaseName: flex_pay_database
    user: flex_pay_database_user
services:
  - type: web
    name: Kora-flex-pay
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Kora-flex-pay
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
